source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'TraineeTestTask' do
    use_frameworks!
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'KVNProgress'
    pod 'Lockbox'
    pod 'TPKeyboardAvoiding'
    pod 'UIScrollView-InfiniteScroll'
    pod 'netfox'
end